### ISSUE TITLE
vanilla datatables closed down?

### ISSUE THREAD

**Issue by johanneswilm** [Mobius1/Rangeable#1]
Hey,
sorry, I could not find any other way to get in touch with you @Mobius1 as your domain also seems to be gone. I noticed you archived the Vanilla Datatables repo. Does this effectively mean that you have closed down the project? Should I continue development under a new name and publish it on npmjs under that new name as well if I need it?

**Comment by Mobius1** [comment]
It's temporary while i work on v2.

**Comment by johanneswilm** [comment]
ok, maybe an idea to put a note in the repo? For people who make use of it, the current message looks a bit disastrous and others may end up releasing forks because they think it's dead.
